### ISSUE TITLE
Shader error in 'Sprites/Outline': '[' : syntax error syntax error at line 88 (on gles)

### ISSUE THREAD

**Issue by easyfast2008** [Elringus/SpriteGlow#11]
This error comes up when unity3d wants to compile under OpenGl. I think it is something with unroll command.

**Comment by easyfast2008** [comment]
In case anyone needs, I solved this by using this
                #if defined (UNITY_COMPILER_HLSL)
                [unroll(10)]
                #endif

I don't know if this works well after build or not, but the error is gone now.

**Comment by elringus** [comment]
Thanks for reporting the issue! It's now fixed with https://github.com/Elringus/SpriteGlow/commit/b1c54d1235651e7a2a1468cf1fd5a8b07b252f50.
