### ISSUE TITLE
Changing GlowColor in script without messing up brightness. 

### ISSUE THREAD

**Issue by umaqs** [Elringus/SpriteGlow#15]
I have a simple sprite (square of white color) and I am setting a random color to its sprite renderer in code. I want to use the same color as GlowColor which works fine for once but when I change GlowColor a couple of times it loses its color brightness resulting in lose of glow.

Here is the code I am using:

    public void Init (Color color) 
    {
        sprite = GetComponent<SpriteRenderer>();
        sprite.color = color;
        SpriteGlow.SpriteGlow glow = GetComponent<SpriteGlow.SpriteGlow>();
        glow.GlowColor = color;
    }

Init method is called multiple times, how can I set glow color so it is visible every time?

PS:  Currently Bloom effect is applied on all the materials. How can I remove the effect from some of materials?

Cheers

**Comment by elringus** [comment]
I've added a glow brightness property, so it's now possible to change color and glow power separately (https://github.com/Elringus/SpriteGlow/commit/e1939b18baea50820022b26f55fe833cec655653). You can download the updated package here: https://github.com/Elringus/SpriteGlow/releases/download/v2.2a-release/SpriteGlow.unitypackage

> PS: Currently Bloom effect is applied on all the materials. How can I remove the effect from some of materials?

Check the 'Threshold' value of the bloom effect: https://github.com/Elringus/SpriteGlow#why-the-glow-appears-on-the-whole-image
