### ISSUE TITLE
Adding a SpriteGlow component from code doesn't work on Android if there's no SpriteGlow in the scene

### ISSUE THREAD

**Issue by hlibr** [Elringus/SpriteGlow#17]
If there's no SpriteGlow in the scene already adding a SpriteGlow component form the script causes a NullReferenceException because SpriteGlowMaterial.OUTLINE_SHADER is null.

**Comment by elringus** [comment]
Most likely the outline shader is not included to the build (it happens when none of the included assets reference SpriteGlow component directly). You can force-include the shader by assigning it to the "Always Included Shaders" in the Edit -> Project Settings -> Graphics.

**Comment by hlibr** [comment]
Yep, that's it, thanks!
