### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by shirkan** [Elringus/SpriteGlow#18]
NullReferenceException
UnityEngine.Material..ctor (UnityEngine.Shader shader) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/ShaderBindings.gen.cs:259)
SpriteGlow.SpriteGlowMaterial..ctor (UnityEngine.Texture spriteTexture, Boolean drawOutside, Boolean instancingEnabled) (at Assets/SpriteGlow/SpriteGlowMaterial.cs:21)
SpriteGlow.SpriteGlowMaterial.GetSharedFor (SpriteGlow.SpriteGlow spriteGlow) (at Assets/SpriteGlow/SpriteGlowMaterial.cs:37)
SpriteGlow.SpriteGlow.SetMaterialProperties () (at Assets/SpriteGlow/SpriteGlow.cs:144)
SpriteGlow.SpriteGlow.OnValidate () (at Assets/SpriteGlow/SpriteGlow.cs:131)

**Comment by elringus** [comment]
Take a look at: https://github.com/Elringus/SpriteGlow/issues/17
