### ISSUE TITLE
bloom force Unity 2017.2

### ISSUE THREAD

**Issue by Avatarchik** [Elringus/SpriteGlow#19]
PC: http://take.ms/yK9jm
Android: http://take.ms/FYDmQ

**Comment by elringus** [comment]
Check for the active color space on PC and Android. It could be you're using linear on PC and gamma on Android, hence the difference in brightness.

**Comment by Avatarchik** [comment]
Editor(Android):http://take.ms/dSuG7
Nexus 4: offset http://take.ms/CKEsA
Xiaomi Redmi 4: http://take.ms/RPo4b

**Comment by elringus** [comment]
Bloom effect is not really a part of this project and it's visual quality depends on multiple factors.
To fix the offset issue you may try enabling pixel snap for the sprite material.
