### ISSUE TITLE
outline size

### ISSUE THREAD

**Issue by Avatarchik** [Elringus/SpriteGlow#20]
Editor:http://take.ms/MqwPy
Android (Nexus 4):http://take.ms/ySFK8
Settings:http://take.ms/CwGGo
If to specify opengl es2 that all is normal but ate opengl 3 that leaves a problem ...

**Comment by elringus** [comment]
Unfortunately, I wasn't able to reproduce the issue. Please make sure to use the latest release built with Unity 2017.3.
