### ISSUE TITLE
I can't add the ScriptGlow script to a Tilemap

### ISSUE THREAD

**Issue by DanTe1794** [Elringus/SpriteGlow#21]
The system is great and I'm very satisfied, but I noticed I can't use it on tilemaps. 

Unity displays the LogError message: "Can't add component 'SpriteRenderer' to Tilemap because it conflicts with the existing "TilemapRenderer" derived component!", which makes it pretty obvious that the problem is with the TilemapRenderer.

I'm still new in Unity and slowing learning all the small bits, so please forgive me if this is a silly question, but is there a workaround to apply this System on a Tilemap? Thanks!

**Comment by elringus** [comment]
I'm afraid this effect only works with SpriteRenderers, sorry.

**Comment by elringus** [comment]
Actually, after messing a bit with the tilemaps, I've found a way to apply the effect. You can assign a custom sprite outline material to TileMap renderer and control the params via material editor. Notice though, that all the tiles in the map will share the same params. I've added an example on how to use this to the project (scene 'TilemapExample').

**Comment by DanTe1794** [comment]
Oh, nice! Thanks!
