### ISSUE TITLE
Shader Problem

### ISSUE THREAD

**Issue by Fineallday** [Elringus/SpriteGlow#22]
When I add the Sprite Glow Effect (Script) 
I get this error:
Shader error in 'Sprites/Outline': not enough actual parameters for macro 'UNITY_ACCESS_INSTANCED_PROP' undeclared identifier 'UNITY_ACCESS_INSTANCED_PROP' at line 222 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS UNITY_NO_CUBEMAP_ARRAY UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME

Thanks!

**Comment by elringus** [comment]
Please make sure you're using compatible Unity version. Latest release only works with Unity 2017.3 and higher. For previous Unity versions support check out the releases page: https://github.com/Elringus/SpriteGlow/releases

**Comment by Fineallday** [comment]
You are right! I'm using 2017.2! 
And was trying SpriteGlow 2.3.
Thanks,
