### ISSUE TITLE
i dont know how to fix

### ISSUE THREAD

**Issue by stickylabdev** [Elringus/SpriteGlow#23]
![screenshot_63](https://user-images.githubusercontent.com/13078369/37634088-9ee05c50-2c27-11e8-8b74-4874705be587.png)

**Comment by Elringus** [comment]
Take a look at: https://github.com/Elringus/SpriteGlow/issues/22

**Comment by elringus** [comment]
Duplicate of #22

**Comment by stickylabdev** [comment]
is this really work on android ?

**Comment by elringus** [comment]
Well, it should work on any platform with SM2.0 and HDR support. Performance will vary depending on the bloom solution, though. It worked fine on my xperia android tablet.
