### ISSUE TITLE
Modify to work with Image instead of SpriteRenderer?

### ISSUE THREAD

**Issue by gen3vra** [Elringus/SpriteGlow#24]
Hello! Is it possible to use this same effect with Images instead of SpriteRenderers? Thanks.

**Comment by elringus** [comment]
Hi, It's possible (if you're ok applying post processing to the UI layers), but requires a bit of manual work. If you wish to try this, the easiest way would be creating a material with the `Sprites/Outline` shader and assigning it to the 'Material' property of the `Image` component. You can then control all the glow parameters via the material editor. I've added an [example scene](https://github.com/Elringus/SpriteGlow/blob/master/Assets/Scenes/UIExample.unity) to the project, so you can check it out.

![](https://i.gyazo.com/6c92f315d8a25600bf4ec930c5b7de3e.png)

**Comment by gen3vra** [comment]
Excellent! Thank you so much for adding that example. I appreciate it.
