### ISSUE TITLE
Feature Request: Support Child Sprites

### ISSUE THREAD

**Issue by drdavient** [Elringus/SpriteGlow#25]
If we have multiple sprites the glows generated will overlay one another. See center of RHS image
Desired effect would be a combined sprite so that a single outline is created. See center of LHS of image.

![image](https://user-images.githubusercontent.com/4351544/38045004-4adbb8ba-32b3-11e8-9385-b8056ccebc7b.png)

Even better - would be to enable placing these glows on separate layers? THough This may be far too complex?

**Comment by elringus** [comment]
I don't think that's possible, unfortunately. At least, without using stencil buffer or some other ways to "communicate" between sprites. I think you need some custom solution here, tailored for you specific needs.
