### ISSUE TITLE
How to make that dirty lens effect shown on the readme ?..

### ISSUE THREAD

**Issue by wasplay** [Elringus/SpriteGlow#26]
![68747470733a2f2f692e6779617a6f2e636f6d2f63386638656338613237366161343738316235323733326335323136393164622e676966](https://user-images.githubusercontent.com/37506355/39387478-13e43a88-4a7a-11e8-9a3f-e5923e443460.gif)

I managed to reproduce the bloom but i can't find any way to do that dirty lens effect

**Comment by elringus** [comment]
Just use any dirty lens post processing effect. Eg, the one from https://github.com/Unity-Technologies/PostProcessing.

**Comment by wasplay** [comment]
Ok thanks :)
