### ISSUE TITLE
2017.1.1 nonsupport UI Glow

### ISSUE THREAD

**Issue by XiaoFanJX** [Elringus/SpriteGlow#27]
I am using UNITY 2017.1.1 but only 2018 in the instance supports UIGlow. Is there any way to convert it?

**Comment by elringus** [comment]
Make sure you're using compatible Unity version. Latest release only works with Unity 2017.3 and higher. For previous Unity versions support check out the releases page: https://github.com/Elringus/SpriteGlow/releases
