### ISSUE TITLE
Mobile devices.

### ISSUE THREAD

**Issue by iozsaygi** [Elringus/SpriteGlow#29]
Hi , firstly thanks for creating great assets.
Is "SpriteGlow" also usable for mobile devices ?
Asking for performance.

**Comment by elringus** [comment]
Hi, The performance will mostly depend on which bloom solution you'll choose. The Unity's PPS Bloom effect has an optimization option for mobile devices, so it should work fine.

**Comment by iozsaygi** [comment]
Thanks :-)
