### ISSUE TITLE
rendering issues with overlapping layers

### ISSUE THREAD

**Issue by ghost** [Elringus/SpriteGlow#30]
I'm using the Unity PPS bloom and any time the effect overlaps with another object it creates really bad colour distortions and bloom size changes, sometimes blotting out the entire screen. any idea if I just have this set up wrong or what might be causing that? Thanks!

https://i.imgur.com/bL1DQ2i.png
https://i.imgur.com/zcjquYQ.png

**Comment by elringus** [comment]
On the first screenshot I can't really see any issues. The middle character has a weird outline, but looks like the outline color is set to black? Bloom won't work properly with blacks, I guess.

Regarding bloom size changes: depending on the material, when HDR colors overlap, it could brighten the bloom effect. It doesn't really have anything to do with the SpriteGlow, but rather with the chosen bloom effect implementation.

**Comment by ghost** [comment]
Thanks for the quick response! Yeah I suppose it's kinda hard to tell what's going on in a still image. The sprites on the left actually have a white outline.  

Here's what I mean in a short video using your demo scene:
https://gfycat.com/SeparatePettyAmericanratsnake

**Comment by elringus** [comment]
Oh, now that's look interesting! I'll make sure to check this out, thanks for letting me know :)

**Comment by elringus** [comment]
The issue is now fixed in the latest release: https://github.com/Elringus/SpriteGlow/releases/tag/v1.6-release

**Comment by ghost** [comment]
Awesome, that did the trick! Thanks!
