### ISSUE TITLE
Material SpriteOutline doesn't have _Stencil property

### ISSUE THREAD

**Issue by hex** [Elringus/SpriteGlow#31]
Hi there, great plugin! I am trying to use this with Unity UI but I get this warning. Is there any way to add Stencil support? 

Thank you!

**Comment by elringus** [comment]
Hi, This plugin is not really intended to be used with UI, hence the name **Sprite**Glow :)
Unity's default sprite shader (which is used as the base for the sprite glow shader) doesn't have stencil properties, so for the best compatibility and upgradability I don't think it's a good idea to add them. But if you're only concerned by the warnings and don't need the UI's masking feature, you can try to copy-paste stencil properties from the default UI shader; this should be enough to prevent the warnings (masks still won't work though).
