### ISSUE TITLE
Glow not working

### ISSUE THREAD

**Issue by LeonardoADS08** [Elringus/SpriteGlow#32]
I dont really know why the script isn't working, i'm using Unity 2018.2.13f1:

The sprite:
![image](https://user-images.githubusercontent.com/12341837/47681091-f534e400-db9e-11e8-914f-e817c0004724.png)

Configurations on inspector:
![image](https://user-images.githubusercontent.com/12341837/47681133-109fef00-db9f-11e8-88b0-00870515d40c.png)

HDR in graphics is checked:
![image](https://user-images.githubusercontent.com/12341837/47681194-3af1ac80-db9f-11e8-8e68-50714c9a8499.png)

Camera also have checked Allow HDR:
![image](https://user-images.githubusercontent.com/12341837/47681282-70969580-db9f-11e8-8593-001fbd18bb04.png)

**Comment by elringus** [comment]
Can you also share your bloom settings please?

**Comment by LeonardoADS08** [comment]
![image](https://user-images.githubusercontent.com/12341837/47688469-ca0cbd80-dbbb-11e8-9361-36973176beab.png)

Edit: Ok, i make it work, but looks weird
![image](https://user-images.githubusercontent.com/12341837/47689177-24f3e400-dbbf-11e8-9f50-247a17303230.png)

**Comment by elringus** [comment]
Try playing with bloom and outline params to make the outline less visible.
