### ISSUE TITLE
Couldn't add in SpriteGlowMaterial.

### ISSUE THREAD

**Issue by awesome1998** [Elringus/SpriteGlow#34]
So far I can add in the SpriteGlowEffect into my sprite. But I couldn't add in SpriteGlowMaterial, it says the script needs to derive from MonoBehaviour. I tried changing the word Material from the public class into MonoBehaviour, but most lines have errors. Is there anyway to solve this?

![image](https://user-images.githubusercontent.com/46670606/51103455-b7e70680-181d-11e9-881f-bcd3e98fec75.png)

**Comment by elringus** [comment]
`SpriteGlowMaterial` is not a `MonoBehaviour` and can't be added to a gameobject. To apply the effect, you just have to add `SpriteGlow` component.

**Comment by awesome1998** [comment]
Remind me how do I add the component again? Sorry I'm not really good at Unity, but happened to stumble upon this. I'm not sure if this is the right way to do it.
![image](https://user-images.githubusercontent.com/46670606/51152753-2670a680-18a8-11e9-8dad-13d5a30c20d5.png)

**Comment by elringus** [comment]
You do it in the editor: https://docs.unity3d.com/Manual/UsingComponents.html
