### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by Shaafee** [Elringus/SpriteGlow#35]
I want to implement this to the 2D game I'm developing. I'm kinda new to this. If you could elaborate on the workflow a bit. I'm confused about the material that I've to create, you've mentioned it in the Description.  Any help is appreciated.

**Comment by elringus** [comment]
Just add a `SpriteGlow` component to a sprite and make sure bloom solution is configured correctly. Check out test project (from this repository) for the examples.

**Comment by Shaafee** [comment]
I've downloaded Post Processing effect from Asset store. Attached it to camera, adjusted the bloom settings as per instruction. But nothing is happening.

**Comment by elringus** [comment]
Check out the test project for the post processing setup example.

**Comment by Shaafee** [comment]
I'm using Unity 2017.2.0f3 therefore I downloaded Sprite Glow Version 1.2. And I can't seem to find the test project in that. Do I have to download the latest package for the test project?

**Comment by elringus** [comment]
Test project is only available for the latest Unity version and is contained in this repository.

**Comment by Shaafee** [comment]
I'll update and try it. Thanks.
