### ISSUE TITLE
Unity Post-Processing Stack v2 support/guide

### ISSUE THREAD

**Issue by theTreeSerok** [Elringus/SpriteGlow#36]
With the newer Post-Processing Stack introduced in 2018.1, it seems that either this package doesn't support it, or there's a different setup required - I couldn't seem to figure it out and get it working, but I'm a little bit of a novice when it comes to the fine intricacies of the PPS. 

Maybe some clarification in the help/troubleshooting/support area for v2?

In the meantime, the legacy PPS works awesome!

**Comment by elringus** [comment]
I think I've initially tested it with the v2 of the stack. All the screenshots in the docs are from this version.

**Comment by elringus** [comment]
Just checked with the latest Unity and PPS versions, everything seems to work fine. Try cloning the repository project and check out the setup.

**Comment by theTreeSerok** [comment]
Ah I see now, this makes more sense. The PPSv2 docs are somewhat vague so I was just setting it up wrong, which is what I assumed really.

This clears it up - awesome asset - thank you!
