### ISSUE TITLE
Copied all resources from example project, still not working

### ISSUE THREAD

**Issue by ypamacedo** [Elringus/SpriteGlow#37]
I've copied every single parameter, object, asset, and project setting I could find in the example project. Still, I can get no more than this punny outline around the character's head: 

![GlowHelp](https://user-images.githubusercontent.com/13225085/56474705-b26c0e80-6453-11e9-9ea8-9a4d1295ff73.png)

It's my first time attempting this post processing wizardry, and I would be very thankful if it could be just a rookie mistake.

**Comment by elringus** [comment]
Make sure HDR is enabled in the SRP config asset.

**Comment by elringus** [comment]
And by the way, SRP is not required for the effect, so you can just disable it (remove the SRP asset from the grpaphic config window).

**Comment by ypamacedo** [comment]
It was on. I had copied that one as well. Still nothing :<

![GlowHelp](https://user-images.githubusercontent.com/13225085/56501393-fd823200-64e4-11e9-99af-0fb04ea5f55b.png)

**Comment by elringus** [comment]
Well, then I'm out of ideas. Does the project from this repo works fine for you?

**Comment by elringus** [comment]
Try checking out the object layers. I thinks PPS is using them in some way.

**Comment by ypamacedo** [comment]
Yes, the project on the repo works and looks perfect. Great job on that :)

Found out what the problem was. I didn't change the Post Process Volume component's GameObject to the PostProcessing object layer

**Comment by elringus** [comment]
Glad you've made it work!
