### ISSUE TITLE
Outline took 2 pixels instead of 1

### ISSUE THREAD

**Issue by leducanhh** [Elringus/SpriteGlow#38]
Hi, I don't know this is my issue only, or it's your ideal shader. Please help me about shader, I need 1 outline pixel only. Thanks!
[https://www.dropbox.com/s/g8kjkwju0mjdda6/outline_size.PNG?dl=0](url)

**Comment by elringus** [comment]
The outline width is in texels (texture pixels) so the actual width in screen pixels will depend on the texture resolution, PPU, scale, position in the world, camera mode, etc. Hence, it's not possible to control the pixel width directly with this solution.

**Comment by leducanhh** [comment]
When I write (Inside) Outline shader by myself, I got a problem about the outline at the boundary of the sprite. Do you have any suggestions for me? Thank for replying to me!
https://www.dropbox.com/s/gjhdcuroij4cuv3/outline_border.PNG?dl=0

**Comment by elringus** [comment]
Could be an algorithm issue. Feel free to use the outline drawing code from this solution, it should work correctly.

**Comment by leducanhh** [comment]
I figured it out your shader script. Got this comment
"Also checking if sampled fragment is out of the texture space (UV is out of 0-1 range); considering such fragment as sprite border."
So that is my problem, I have a lack of knowledge about this. Can you enlight me about this, please sir? How can i know that is the fragment which outside of the texture space?

**updated**: Holy shiet... i made it. Thanks for your script, hail Elringus, hail google!

**Comment by elringus** [comment]
You're welcome :)
