### ISSUE TITLE
Android Issue : sprite pink

### ISSUE THREAD

**Issue by TheKassaK** [Elringus/SpriteGlow#39]
I tried for many hours to find a solution but i'm out of ideas !

I'm working on Unity 2018, SpriteGlow 1.6 (and it's the same with 1.7).

I have the processing stack enabled on my project, and a sprite with a glow effect.

It's ok in my editor and in play mode and it's ok when I build for Windows, I can see the glow effect.

But when I build for Android and try the .apk on Android Studio, the sprite with the SpriteGlowEffect script is pink.

I manually added the shader Sprite/Outline in Graphics settings but no effect.

Do you have an idea ? Tthanks !

**Comment by elringus** [comment]
There could be shader errors or the shader itself is missing. Try reading the device logs to find out more.
