### ISSUE TITLE
2019.3 Support

### ISSUE THREAD

**Issue by ypamacedo** [Elringus/SpriteGlow#40]
It seems to no longer work on 2019.3. Is there something else I need to configure for the URP?

**Comment by elringus** [comment]
Actually it works; it's just the updated LWRP (URP) now requires a special post-processing setup; check the guide for more info: https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.1/manual/integration-with-post-processing.html 

I've updated the example project for Unity 2019.3 and URP.
