### ISSUE TITLE
Unity performance slows down to 25 fps after adding glow effect.

### ISSUE THREAD

**Issue by Jab-Punch** [Elringus/SpriteGlow#41]
Hi. It took a while, but I managed to add the glow effect you provided to a sprite in my 2D game after installing the package, setting the post-processing volume/layers and assigning the sprite outline. It seems to have a use for what I'm looking for and runs well.

However, this game was meant to run at 60 frames per second, and it was running very well at the beginning. With this whole glowing effect added however, the game now runs between 20 to 30 frames, which is unbearable to watch. I'm leading to believe this has to do with the addition of the bloom effect, as I have not implemented lighting effects yet. Furthermore, the game seems to only cause this slowdown of performance when operating under the Unity Editor. I tested building the game into an executable file and it thankfully started working at the 60 fps I expected. Regardless, I want to continue testing the game in the editor without this setback of performance rate, as it would take too long to test each update in a new build.

My overall questions are, was this sprite glow addition meant to function in a lower frame rate? Are there methods I can consider to reduce the performance issues in result of this add-on shader? Any advice on how to keep projects running smoothly after applying the bloom effect would be very helpful. Thank you.

**Comment by elringus** [comment]
It's most likely some issue with the Unity's PPS stack slowing down the editor; make sure you're using latest available Unity and PPS package versions. Also, check the issue tracker for similar issues; if you won't find any, consider submitting a bug report to Unity.
