### ISSUE TITLE
Works in scene view but not through camera. 

### ISSUE THREAD

**Issue by JimZeeKing** [Elringus/SpriteGlow#42]
Hi there, is there any reason why the effect could be seen in scene view but not through the camera?

 Is it because a 2d renderer is use?
I am trying to include it in a urp project that use a 2d renderer data

**Comment by Elringus** [comment]
Afaik, in URP you have to enable post-processing in the scene view to see it.

**Comment by elringus** [comment]
There could be an issue in the configuration. Check the example project in this repo for the reference.

**Comment by JimZeeKing** [comment]
Found the issue, URP use its own post-processing stack and doesnt work yet with PP v2.
Add to use the post processing stack of URP and it works.

Thank you!
