### ISSUE TITLE
Can't import package

### ISSUE THREAD

**Issue by helloroy** [Elringus/SpriteGlow#43]
Hi, the plugin look great, but I can't import to Unity with following error:

```
Cannot perform upm operation: Unable to add package [https://github.com/Elringus/SpriteGlow.git#package]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

```
Error adding package: .
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

Do you have other method to suggest to import the package?

Thanks a lot

**Comment by elringus** [comment]
You have the answer right inside the error you've shared. Please read carefully:

> No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound]

**Comment by helloroy** [comment]
Sure I have read the error message and I have git also, but seems this is Unity package manager problem, why not add to Unity assets to take more impressions and seems the installion will be more easier.

Anyway, I can use your plugin by download manually from Github and copy it to Unity project folder.

Thanks for your great plugin.

**Comment by elringus** [comment]
I've added package to the installation methods, thank you for the suggestion!
