### ISSUE TITLE
Works in scene view but not through camera(not the same as #41)

### ISSUE THREAD

**Issue by Suya1671** [Elringus/SpriteGlow#44]
when I create a material and set it to an image in the scene view the glow work, but in game view it does not, but bloom work just fine on everything else. URP 7.3.1 and in 2019.3.

Video showing the problem: [https://www.dropbox.com/s/8d5col4tvhs0jgd/yJVJZkgwyk.mp4?dl=0](url)

**Comment by elringus** [comment]
This is a Unity issue, please report to them.

**Comment by Suya1671** [comment]
currently sending them it, any idea why this might not work?
