### ISSUE TITLE
Can't add component 'SpriteRenderer' to x because if conflicts with the existing 'MeshFilter' derived component!

### ISSUE THREAD

**Issue by filiptronicek** [Elringus/SpriteGlow#45]
When I'm trying to add the sprite to a custom layer unity freaks out and throws this error: `Can't add component 'SpriteRenderer' to x because if conflicts with the existing 'MeshFilter' derived component!`
![image](https://user-images.githubusercontent.com/29888641/82128139-1a0c9e80-97b9-11ea-8431-7fb3e1df381e.png)

**Comment by elringus** [comment]
How's that related with the plugin?
