### ISSUE TITLE
Is not work in Mobile device! 

### ISSUE THREAD

**Issue by naylinhtun1** [Elringus/SpriteGlow#49]
I build a apk work with this asset and I run this on my mobile and it's not work and also weird thing happen but Unity editor it's perfectly work! if you can fix that it's awesome

**Comment by elringus** [comment]
Please share the full log from the device (don't forget to enable debug build).

**Comment by naylinhtun1** [comment]
Oh my god! thanks for reply! wait please I'm next time testing

**Comment by naylinhtun1** [comment]
you mean script debugging in development build

**Comment by naylinhtun1** [comment]
I got any logs from my device I'm so sad bro your assets is pretty awesome if it can run on device

**Comment by naylinhtun1** [comment]
Can you fix that? I really really thankful to you

**Comment by elringus** [comment]
> 
> 
> Can you fix that? I really really thankful to you

Not without the logs. Try googling on how to extract the debug logs from the device.
