### ISSUE TITLE
Cant get UIExample to work in SpriteGlow-1.8 or 1.7

### ISSUE THREAD

**Issue by Spannerworx** [Elringus/SpriteGlow#51]
Hi, cool product, thank you! I am trying to get this working on my UI (buttons etc) for Built-In rendering, but having some issues on Unity 2019.4.7:

In SpriteGlow-1.8, in the UIExample scene, the LegacyCamera does not show the glow effect. I took these steps:

1) I disabled URPCamera and enabled LegacyCamera
2) I ticked Post Processing on the LegacyCamera
3) I set the Render Camera of the Canvas to LegacyCamera

See [screenshot SpriteGlow_1_8_Issue](https://manualintervention.com/screens/SpriteGlow_1_8_Issue.PNG)
The example scenes work fine apart from UIExample. Am I missing something?

Just for reference, I also tried a previous version, but in SpriteGlow-1.7, none of the example scenes work.
See [screenshot SpriteGlow_1_7_Issue](https://manualintervention.com/screens/SpriteGlow_1_7_Issue.PNG)

Thanks for your help.

**Comment by elringus** [comment]
Could be a regression in Unity, try with previous/newer versions (it definitely worked back in 2019.3); consider submitting a bug report to Unity if you find it's working in the other versions.
