### ISSUE TITLE
About the Line Renderer

### ISSUE THREAD

**Issue by chaoslejyonu** [Elringus/SpriteGlow#52]
Can we apply this to line renderer for 2d? When I add the Sprite Glow script, it automatically adds the new material to the sprite renderer (Sprites/Outline), can we create this material instead of adding with the script so that we can add this material to the line renderer?

**Comment by elringus** [comment]
It's possible; see the FAQ for more info: https://github.com/Elringus/SpriteGlow#can-i-use-the-effect-with-components-other-than-spriterenderer-ui-image-tilemap-etc
