### ISSUE TITLE
Not working for my project setup for android

### ISSUE THREAD

**Issue by umitpradhan** [Elringus/SpriteGlow#54]
I am getting this error whenever trying to increase the glow.

NullReferenceException: Object reference not set to an instance of an object
SpriteGlow.SpriteGlowMaterial.GetSharedFor (SpriteGlow.SpriteGlowEffect spriteGlow) (at Library/PackageCache/com.elringus.spriteglow@05442994ff/Runtime/SpriteGlowMaterial.cs:38)
SpriteGlow.SpriteGlowEffect.SetMaterialProperties () (at Library/PackageCache/com.elringus.spriteglow@05442994ff/Runtime/SpriteGlowEffect.cs:98)
SpriteGlow.SpriteGlowEffect.OnValidate () (at Library/PackageCache/com.elringus.spriteglow@05442994ff/Runtime/SpriteGlowEffect.cs:85)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by elringus** [comment]
Maybe the game object to which the effect is applied is missing sprite renderer component or the sprite/texture?
