### ISSUE TITLE
Thick, white outline around player.

### ISSUE THREAD

**Issue by CameronCheney** [Elringus/SpriteGlow#56]
I have this script added to my player and I am using URP, and it's built in Post-Processing. I'm not sure if this was made for that, but I seems to almost work. The issue, is that I have this thick white outline around the object I have added the script to(player). I notice if I turn the bloom intensity high enough and the threshold low enough, I can see the glow, but only when the white out line is there. I have tried setting the alpha of the image to 1 or zero, and it lights back up when I turn of the intensity. Here is a screenshot of what I'm talking about. In this example, I use bloom tinted red, to show that it is working, and to make it more obvious:
![playerwhiteoutline](https://user-images.githubusercontent.com/56519868/149864554-c0e57c38-e7e7-4d5e-854e-1620ce62be2b.PNG)
![script on player](https://user-images.githubusercontent.com/56519868/149864563-7043a643-717e-466a-a01c-b040079f91cc.PNG)

**Comment by elringus** [comment]
That's the way the effect works: it draws and HDR outline over the sprite borders, which is then picked by bloom post-effect. The lower the sprite resolution, the more noticeable the outline would be.

**Comment by CameronCheney** [comment]
Is there anyway to make it smaller? it just barely noticeable? If not do you have any other possible solutions on how to add bloom to individual sprites like that? Thanks for you help!

**Comment by elringus** [comment]
It can't be smaller than 1 pixel.

**Comment by CameronCheney** [comment]
So, my sprite's image is enlarged by 8 times on the x and y axis. Is there a way to make it it's own image? Because technically it isn't taking up only one pixel on the screen of course, and if it was it's own image, maybe there would be a way to size it down. Or make it thinner some how. Otherwise, it seems the only solution would be to make the player literally be drawn with more pixels/ be drawn bigger.
