### ISSUE TITLE
Sprite Glow not Glowing? (Unity 2021.3.24f1)

### ISSUE THREAD

**Issue by BrennanK07** [Elringus/SpriteGlow#59]
Having an issue with the sprite glow package on a sprite in my game. I can get the outline to appear, but no lighting is given off from it.

**Expected behavior**
Should glow on the surrounding area

**Screenshots**
![image](https://github.com/Elringus/SpriteGlow/assets/70231079/52f3f147-2d97-4644-9072-a5fd9a61cae7)

**Environment (please complete the following information):**
 - Unity version: 2021.3.24f1
 - OS: Windows 11

**Additional context**
I do have URP in the scene and it does work

**Comment by elringus** [comment]
Check the readme for troubleshooting steps. If it won't help, check the example project, it has URP setup.
