### ISSUE TITLE
Dont work on android

### ISSUE THREAD

**Issue by natsupy** [Elringus/SpriteGlow#7]
Hi, when i'm switch to android, image effect doesnt work like platform pc, but when i try with kinobloom of Takahashi, bloom view to good, so what issue of this
https://github.com/keijiro/KinoBloom

**Comment by elringus** [comment]
There seems to be a regression issue with the HDR rendering in Unity 5.6; could be related to this case: https://issuetracker.unity3d.com/issues/bloom-not-working-with-hdr-and-bloom-threshold-at-1 

Not sure if there are any workarounds other then using previous engine versions (checked it with Unity 5.4 and it works fine there on both Android and iOS).

**Comment by natsupy** [comment]
thank you for info, i'll try back 5.4 current is 5.6.1p2

**Comment by natsupy** [comment]
i checked with 5.4.5f1, and not work on pc too
http://i.imgur.com/6mUHwVa.png

**Comment by elringus** [comment]
Make sure you're using a 5.4-compatible bloom solution and it's correctly configured.

**Comment by elringus** [comment]
https://github.com/Elringus/SpriteGlow/issues/13
