### ISSUE TITLE
Glow not happenning on outlines

### ISSUE THREAD

**Issue by No3371** [Elringus/SpriteGlow#8]
![default](https://user-images.githubusercontent.com/1814971/28308887-398957ac-6bda-11e7-8221-84bfe160e0b4.png)
Everything is glowing instead of just outlines, how can I fix this?

**Comment by elringus** [comment]
Make sure bloom threshold is set to something like 1.5 or more. Also, there is an issue with HDR rendering on mobiles on Unity 5.6 and 2017.1: https://github.com/Elringus/SpriteGlow/issues/7

**Comment by elringus** [comment]
A small update on the matter: an issue was found, which breaks HDR rendering when editor mode is set to 2D (Edit -> Project Settings -> Editor -> Default Behavior Mode): https://issuetracker.unity3d.com/issues/setting-default-behavior-mode-to-2d-breaks-hdr-rendering 
Setting behavior mode to 3D should resolve the problem.

So, aside from mobile HDR rendering issue, we also have this one, but at least in this case there is a workaround.
