### ISSUE TITLE
Behaves Like Any Other Sprite

### ISSUE THREAD

**Issue by KeyTry** [Elringus/SpriteGlow#9]
I read the replies to some of the other issues, but none seems to solve it.

When I add the Sprite Glow component to the sprite, it creates an outline outside of it:
![1](https://user-images.githubusercontent.com/15346451/31322699-0479cf86-ac5a-11e7-8132-6b0469a2da67.PNG)

But modifying the Bloom effect using the Unity PostProccessing stack doesn't have any effect on the sprite I want to glow, instead it has the same effect on every Sprite:
![2](https://user-images.githubusercontent.com/15346451/31322714-4b615aa4-ac5a-11e7-8085-55181c3a665d.PNG)

**Comment by elringus** [comment]
Make sure bloom threshold is high enough (1 or more, depending on the bloom solution) and camera HDR toggle is enabled. Also, Unity 5.6-2017.1 has an issue with HDR when editor is in 2D behavior mode, so try switching it to 3D (in case you missed this one on the other issue).

**Comment by ajayyy** [comment]
I'm having the same issue, have you solved it @KeyTry ?

Found the answer here: https://github.com/Elringus/SpriteGlow/issues/1

Had to change the brightness value.
